Repository FreshManProject/FreshManBackend, pull requests merged in 2024-07, with the labels that each got.

#1 [FEAT] 기본 세팅 추가
  build.gradle
  src/main/java/com/freshman/freshmanbackend/global/common/domain/BaseTimeEntity.java
  src/main/java/com/freshman/freshmanbackend/global/common/response/DataListResponse.java
  src/main/java/com/freshman/freshmanbackend/global/common/response/DataResponse.java
  src/main/java/com/freshman/freshmanbackend/global/common/response/ErrorResponse.java
  src/main/java/com/freshman/freshmanbackend/global/common/response/ListResponse.java
  src/main/java/com/freshman/freshmanbackend/global/common/response/SuccessResponse.java
  src/main/java/com/freshman/freshmanbackend/global/common/utils/DateTimeUtils.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 설정 추가

#3 [FEAT] 상품 관련 엔티티 및 Enum Converter 추가
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/Product.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/ProductCategory.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/ProductImage.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/ProductSale.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/enums/ProductImageType.java
  src/main/java/com/freshman/freshmanbackend/domain/product/repository/ProductRepository.java
  src/main/java/com/freshman/freshmanbackend/global/common/domain/converter/AbstractEnumCodeConverter.java
  src/main/java/com/freshman/freshmanbackend/global/common/domain/enums/Codable.java
  src/main/java/com/freshman/freshmanbackend/global/common/domain/enums/Valid.java
Labels: 엔티티 추가

#4 [FEAT] Querydsl 설정 추가
  .gitignore
  build.gradle
  src/main/java/com/freshman/freshmanbackend/global/common/config/QuerydslConfig.java
Labels: 설정 추가

#5 [FEAT] 상품 및 카테고리 등록/목록 조회 API 구현
  src/main/java/com/freshman/freshmanbackend/FreshmanBackendApplication.java
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/ProductController.java
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/validator/ProductValidator.java
  src/main/java/com/freshman/freshmanbackend/domain/product/dao/ProductListDao.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/enums/ProductSortType.java
  src/main/java/com/freshman/freshmanbackend/domain/product/repository/ProductCategoryRepository.java
  src/main/java/com/freshman/freshmanbackend/domain/product/request/ProductCategoryEntryRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/product/request/ProductEntryRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/product/request/ProductListRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/product/response/ProductCategoryListResponse.java
  src/main/java/com/freshman/freshmanbackend/domain/product/response/ProductListResponse.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/ProductCategoryEntryService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/ProductCategoryListService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/ProductCategoryOneService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/ProductEntryService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/ProductListService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/ProductOneService.java
Labels: API 추가, 설정 추가

#6 [FEAT] MessageSource를 사용한 예외 핸들러 구현
  build.gradle
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/validator/ProductValidator.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/ProductCategoryOneService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/ProductOneService.java
  src/main/java/com/freshman/freshmanbackend/global/common/exception/ValidationException.java
  src/main/java/com/freshman/freshmanbackend/global/common/exception/handler/RestApiExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/messages/validation.properties
Labels: 설정 추가

#7 [FEAT] 상품 및 카테고리 수정/삭제 API 구현
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/ProductController.java
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/validator/ProductValidator.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/Product.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/ProductCategory.java
  src/main/java/com/freshman/freshmanbackend/domain/product/repository/ProductRepository.java
  src/main/java/com/freshman/freshmanbackend/domain/product/request/ProductCategoryModifyRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/product/request/ProductModifyRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductCategoryDeleteService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductCategoryEntryService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductCategoryModifyService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductDeleteService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductEntryService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductModifyService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/query/ProductCategoryListService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/query/ProductCategoryOneService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/query/ProductListService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/query/ProductOneService.java
  src/main/resources/messages/validation.properties
Labels: API 추가

#8 [FEAT] 상품 할인정보 API 구현
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/ProductController.java
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/validator/ProductValidator.java
  src/main/java/com/freshman/freshmanbackend/domain/product/dao/ProductListDao.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/Product.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/ProductSale.java
  src/main/java/com/freshman/freshmanbackend/domain/product/request/ProductSaleRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/product/response/ProductListResponse.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductDeleteService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductEntryService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductModifyService.java
  src/main/java/com/freshman/freshmanbackend/global/common/utils/DateTimeUtils.java
  src/main/resources/messages/validation.properties
Labels: API 추가, 쿼리 수정

#9 [FEAT] 상품 상세 조회 API 구현
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/ProductController.java
  src/main/java/com/freshman/freshmanbackend/domain/product/response/ProductDetailResponse.java
  src/main/java/com/freshman/freshmanbackend/domain/product/response/ProductListResponse.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/query/ProductOneService.java
Labels: API 추가

#11 [FIX] 상품 API PathVariable로 수정
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/ProductController.java
Labels: API 수정

#10 [FEAT] 소셜 로그인, 유저관련 API 구현
  .gitignore
  README.md
  build.gradle
  src/main/java/com/freshman/freshmanbackend/domain/member/controller/MemberController.java
  src/main/java/com/freshman/freshmanbackend/domain/member/controller/validator/MemberValidator.java
  src/main/java/com/freshman/freshmanbackend/domain/member/domain/Member.java
  src/main/java/com/freshman/freshmanbackend/domain/member/domain/enums/Role.java
  src/main/java/com/freshman/freshmanbackend/domain/member/repository/MemberRepository.java
  src/main/java/com/freshman/freshmanbackend/domain/member/request/MemberUpdateRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/member/response/MemberResponse.java
  src/main/java/com/freshman/freshmanbackend/domain/member/service/MemberService.java
  src/main/java/com/freshman/freshmanbackend/global/auth/config/CorsMvcConfig.java
  src/main/java/com/freshman/freshmanbackend/global/auth/config/SecurityConfig.java
  src/main/java/com/freshman/freshmanbackend/global/auth/controller/JwtReissueController.java
  src/main/java/com/freshman/freshmanbackend/global/auth/dto/CustomOauth2User.java
  src/main/java/com/freshman/freshmanbackend/global/auth/dto/OauthUserDto.java
  src/main/java/com/freshman/freshmanbackend/global/auth/dto/Tokens.java
  src/main/java/com/freshman/freshmanbackend/global/auth/filter/JwtFilter.java
  src/main/java/com/freshman/freshmanbackend/global/auth/filter/JwtLogoutFilter.java
  src/main/java/com/freshman/freshmanbackend/global/auth/handler/LoginSuccessHandler.java
  src/main/java/com/freshman/freshmanbackend/global/auth/response/KakaoResponse.java
  src/main/java/com/freshman/freshmanbackend/global/auth/response/NaverResponse.java
  src/main/java/com/freshman/freshmanbackend/global/auth/response/Oauth2Response.java
  src/main/java/com/freshman/freshmanbackend/global/auth/service/CustomOAuth2UserService.java
  src/main/java/com/freshman/freshmanbackend/global/auth/service/JwtReissueService.java
  src/main/java/com/freshman/freshmanbackend/global/auth/util/AuthMemberUtils.java
  src/main/java/com/freshman/freshmanbackend/global/auth/util/JwtUtil.java
  src/main/java/com/freshman/freshmanbackend/global/common/utils/HttpUtils.java
  src/main/java/com/freshman/freshmanbackend/global/redis/config/RedisConfig.java
  src/main/java/com/freshman/freshmanbackend/global/redis/domain/RedisRefreshToken.java
  src/main/java/com/freshman/freshmanbackend/global/redis/repository/RedisRefreshTokenRepository.java
  src/main/java/com/freshman/freshmanbackend/global/redis/service/RedisRefreshTokenService.java
  src/main/resources/application.yml
  src/main/resources/messages/validation.properties
  src/test/java/com/freshman/freshmanbackend/domain/member/repository/MemberRepositoryTest.java
Labels: API 추가, 설정 추가, 엔티티 추가

#13 [FEAT] 후기 등록 API 구현, Auditor 설정 추가
  src/main/java/com/freshman/freshmanbackend/domain/member/service/MemberService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/ProductController.java
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/validator/ProductValidator.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/Review.java
  src/main/java/com/freshman/freshmanbackend/domain/product/repository/ReviewRepository.java
  src/main/java/com/freshman/freshmanbackend/domain/product/request/ReviewEntryRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ReviewEntryService.java
  src/main/java/com/freshman/freshmanbackend/global/auth/config/SecurityConfig.java
  src/main/java/com/freshman/freshmanbackend/global/auth/handler/LoginSuccessHandler.java
  src/main/java/com/freshman/freshmanbackend/global/auth/service/CustomOAuth2UserService.java
  src/main/java/com/freshman/freshmanbackend/global/auth/util/AuthMemberUtils.java
  src/main/java/com/freshman/freshmanbackend/global/common/audit/MemberAuditorAware.java
  src/main/resources/messages/validation.properties
Labels: API 추가, 설정 추가, 엔티티 추가

#14 [FEAT] 상품 검색 조회 및 최근 검색어 API 구현
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/ProductController.java
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/validator/ProductValidator.java
  src/main/java/com/freshman/freshmanbackend/domain/product/dao/ProductListDao.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/SearchLog.java
  src/main/java/com/freshman/freshmanbackend/domain/product/request/ProductSearchRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/SearchLogService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/query/ProductListService.java
  src/main/java/com/freshman/freshmanbackend/global/auth/config/SecurityConfig.java
  src/main/java/com/freshman/freshmanbackend/global/common/domain/BaseTimeEntity.java
  src/main/java/com/freshman/freshmanbackend/global/redis/config/RedisConfig.java
  src/main/resources/messages/validation.properties
Labels: API 추가

#15 [FEAT] 유효기간이 지난 최근 검색어 삭제 Job 구현
  src/main/java/com/freshman/freshmanbackend/FreshmanBackendApplication.java
  src/main/java/com/freshman/freshmanbackend/batch/job/SearchKeywordDeleteJob.java
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/ProductController.java
  src/main/java/com/freshman/freshmanbackend/domain/product/controller/validator/ProductValidator.java
  src/main/java/com/freshman/freshmanbackend/domain/product/dao/ProductListDao.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/Product.java
  src/main/java/com/freshman/freshmanbackend/domain/product/domain/SearchLog.java
  src/main/java/com/freshman/freshmanbackend/domain/product/response/ProductDetailResponse.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/SearchLogService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductDeleteService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductEntryService.java
  src/main/java/com/freshman/freshmanbackend/domain/product/service/command/ProductModifyService.java
  src/main/java/com/freshman/freshmanbackend/global/common/response/ListResponse.java
  src/main/java/com/freshman/freshmanbackend/global/common/utils/DateTimeUtils.java
Labels: 배치 추가

#16 [FEAT] 장바구니 기능 추가
  src/main/java/com/freshman/freshmanbackend/domain/cart/controller/CartController.java
  src/main/java/com/freshman/freshmanbackend/domain/cart/controller/validator/CartValidator.java
  src/main/java/com/freshman/freshmanbackend/domain/cart/dao/CartDao.java
  src/main/java/com/freshman/freshmanbackend/domain/cart/dao/CartListDao.java
  src/main/java/com/freshman/freshmanbackend/domain/cart/domain/Cart.java
  src/main/java/com/freshman/freshmanbackend/domain/cart/repository/CartRepository.java
  src/main/java/com/freshman/freshmanbackend/domain/cart/request/CartEntryRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/cart/request/CartUpdateRequest.java
  src/main/java/com/freshman/freshmanbackend/domain/cart/response/CartInfoResponse.java
  src/main/java/com/freshman/freshmanbackend/domain/cart/service/CartService.java
  src/main/java/com/freshman/freshmanbackend/domain/member/domain/Member.java
  src/main/java/com/freshman/freshmanbackend/global/auth/config/CorsMvcConfig.java
  src/main/java/com/freshman/freshmanbackend/global/auth/config/SecurityConfig.java
  src/main/resources/messages/validation.properties
  src/test/java/com/freshman/freshmanbackend/domain/member/repository/MemberRepositoryTest.java
Labels: API 추가, 엔티티 추가
